---

timezone: Asia/Tokyo

sshd_server_config_options:
  Protocol: '2'
  PermitRootLogin: 'no'
  PasswordAuthentication: 'no'
  PermitEmptyPasswords: 'no'
  ChallengeResponseAuthentication: 'no'
  UsePAM: 'yes'
  UseDNS: 'yes'
  AcceptEnv:
    - 'LANG LC_*'
  SyslogFacility: 'AUTHPRIV'
  LogLevel: 'VERBOSE'
  IgnoreRhosts: 'yes'
  Subsystem: ""
  X11Forwarding: 'no'
  ListenAddress: '0.0.0.0'
  PubkeyAuthentication: 'yes'
  GSSAPIAuthentication: 'no'
  GSSAPICleanupCredentials: 'no'
  PrintMotd: 'no'
  MaxStartups: '3'
  HostKey:
    - /etc/ssh/ssh_host_ed25519_key
    - /etc/ssh/ssh_host_rsa_key
  Ciphers: chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
  KexAlgorithms: sntrup761x25519-sha512@openssh.com,curve25519-sha256,curve25519-sha256@libssh.org,gss-curve25519-sha256-,diffie-hellman-group16-sha512,gss-group16-sha512-,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha256
  MACs: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128-etm@openssh.com
  HostKeyAlgorithms: ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,sk-ssh-ed25519@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256,rsa-sha2-256-cert-v01@openssh.com

chronyd_server_config_options:
  driftfile: /var/lib/chrony/chrony.drift
  server:
    - '169.254.169.123 prefer iburst minpoll 4 maxpoll 4'
  logdir: /var/log/chrony
  makestep: '1 3'
  rtcsync: ""
  maxupdateskew: 100.0
  local: stratum 10
  keyfile: /etc/chrony/chrony.keys
  logchange: 0.5
  leapsecmode: slew
  maxslewrate: 1000
  smoothtime: 400 0.001 leaponly

sshguard_execmode: 'nftables'

sshguard_config_whitelist:
  - 127.0.0.0/8
  - ::1/128
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.1.0/24

rsyslog_global_config_options:
  - 'module(load="imuxsock")'
  - 'module(load="imklog" permitnonkernelfacility="on")'
  - '$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat'
  - '$RepeatedMsgReduction on'
  - '$FileOwner syslog'
  - '$FileGroup adm'
  - '$FileCreateMode 0640'
  - '$DirCreateMode 0755'
  - '$Umask 0022'
  - '$PrivDropToUser syslog'
  - '$PrivDropToGroup syslog'
  - '$WorkDirectory /var/spool/rsyslog'
  - '$IncludeConfig /etc/rsyslog.d/*.conf'

logrotate_global_config_options:
  - 'weekly'
  - 'su root adm'
  - 'rotate 4'
  - 'create'
  - 'include /etc/logrotate.d'
