
- name: autechgemz.unattended_upgrades
  src: https://github.com/autechgemz/ansible-role-unattended_upgrades.git
  version: 1.0.1

- name: autechgemz.needrestart
  src: https://github.com/autechgemz/ansible-role-needrestart.git
  version: 1.0.1

- name: autechgemz.logrotate
  src: https://github.com/autechgemz/ansible-role-logrotate.git
  version: 1.0.1

- name: autechgemz.journald
  src: https://github.com/autechgemz/ansible-role-journald.git
  version: 1.0.0

- name: autechgemz.sshd
  src: https://github.com/autechgemz/ansible-role-sshd.git
  version: 1.2.0

- name: autechgemz.sysctl
  src: https://github.com/autechgemz/ansible-role-sysctl.git
  version: 1.0.1

- name: autechgemz.sudo
  src: https://github.com/autechgemz/ansible-role-sudo.git
  version: 1.0.1

- name: autechgemz.sshguard
  src: https://github.com/autechgemz/ansible-role-sshguard.git
  version: 1.0.1

- name: autechgemz.timezone
  src: https://github.com/autechgemz/ansible-role-timezone.git
  version: 1.0.0

- name: autechgemz.rsyslog
  src: https://github.com/autechgemz/ansible-role-rsyslog.git
  version: 1.0.1

- name: autechgemz.tcpd
  src: https://github.com/autechgemz/ansible-role-tcpd.git
  version: 1.0.1

- name: autechgemz.auditd
  src: https://github.com/autechgemz/ansible-role-auditd.git
  version: 1.0.1

- name: autechgemz.chronyd
  src: https://github.com/autechgemz/ansible-role-chronyd.git
  version: 1.0.1

- name: autechgemz.apparmor
  src: https://github.com/autechgemz/ansible-role-apparmor.git
  version: 1.0.0
